import type { GestureId } from "@/types/study";

/**
 * GENERATED by scripts/sync_hud_symbols.py from the glasses HUD catalog
 * (catalog_version image_png_v1+octap+no_translate+octap_check_stacked+oc_order+cw_circles(2026-10-01)). Do not edit by hand.
 *
 * `symbol` is exactly what the Rokid HUD prints for that gesture, `inner` is an optional glyph drawn in the
 * MIDDLE of it, and `hudLabel` is the short name beside it - so the depiction an expert judges here is the
 * one they would see on the glasses.
 */
export interface HudMark { symbol: string; hudLabel: string; inner?: string }

export const hudMarks: Record<GestureId, HudMark> = {
  OPS_TAP:         { symbol: "\u25cf", hudLabel: "TAP" },
  OPS_DOUBLE_TAP:  { symbol: "\u25c9", hudLabel: "DOUBLE TAP" },
  OPS_SWIPE_UP:    { symbol: "\u2191", hudLabel: "SWIPE UP" },
  OPS_SWIPE_DOWN:  { symbol: "\u2193", hudLabel: "SWIPE DOWN" },
  OPS_SWIPE_LEFT:  { symbol: "\u2190", hudLabel: "SWIPE LEFT" },
  OPS_SWIPE_RIGHT: { symbol: "\u2192", hudLabel: "SWIPE RIGHT" },
  OPS_CIRCLE:      { symbol: "\u21bb", hudLabel: "CIRCLE" },
  OC_TAP:          { symbol: "\u2713", hudLabel: "OBJ TAP" },
  OC_DOUBLE_TAP:   { symbol: "\u2713\n\u2713", hudLabel: "OBJ 2\u00d7TAP" },
  OC_TILT_UP:      { symbol: "\u2220\u2191", hudLabel: "TILT UP" },
  OC_TILT_DOWN:    { symbol: "\u2220\u2193", hudLabel: "TILT DOWN" },
  OC_TILT_LEFT:    { symbol: "\u2220\u2190", hudLabel: "TILT LEFT" },
  OC_TILT_RIGHT:   { symbol: "\u2220\u2192", hudLabel: "TILT RIGHT" },
  OC_CIRCLE:       { symbol: "\u21bb", hudLabel: "OBJ CIRCLE", inner: "\u25cb" },
};

/** Font stack that actually has these glyphs on Windows, macOS, Linux and Android. */
export const HUD_SYMBOL_FONT = '"Segoe UI Symbol", "Apple Symbols", "Noto Sans Symbols 2", "Noto Sans Symbols", "DejaVu Sans", sans-serif';
