import type { GestureId } from "@/types/study";

/**
 * GENERATED by scripts/sync_hud_symbols.py from the glasses HUD catalog
 * (catalog_version image_png_v1+octap+no_translate+octap_check(2026-10-01)). Do not edit by hand.
 *
 * `symbol` is exactly what the Rokid HUD prints for that gesture and `hudLabel` is the short name beside it,
 * so the depiction an expert judges here is the one they would see on the glasses.
 */
export interface HudMark { symbol: string; hudLabel: string }

export const hudMarks: Record<GestureId, HudMark> = {
  OPS_TAP:         { symbol: "●", hudLabel: "TAP" },
  OPS_DOUBLE_TAP:  { symbol: "◉", hudLabel: "DOUBLE TAP" },
  OPS_SWIPE_UP:    { symbol: "↑", hudLabel: "SWIPE UP" },
  OPS_SWIPE_DOWN:  { symbol: "↓", hudLabel: "SWIPE DOWN" },
  OPS_SWIPE_LEFT:  { symbol: "←", hudLabel: "SWIPE LEFT" },
  OPS_SWIPE_RIGHT: { symbol: "→", hudLabel: "SWIPE RIGHT" },
  OPS_CIRCLE:      { symbol: "↻", hudLabel: "CIRCLE" },
  OC_TILT_UP:      { symbol: "∠↑", hudLabel: "TILT UP" },
  OC_TILT_DOWN:    { symbol: "∠↓", hudLabel: "TILT DOWN" },
  OC_TILT_LEFT:    { symbol: "∠←", hudLabel: "TILT LEFT" },
  OC_TILT_RIGHT:   { symbol: "∠→", hudLabel: "TILT RIGHT" },
  OC_TAP:          { symbol: "✓", hudLabel: "OBJ TAP" },
  OC_DOUBLE_TAP:   { symbol: "✓✓", hudLabel: "OBJ 2×TAP" },
  OC_CIRCLE:       { symbol: "↺", hudLabel: "OBJ CIRCLE" },
};

/** Font stack that actually has these glyphs on Windows, macOS, Linux and Android. */
export const HUD_SYMBOL_FONT = '"Segoe UI Symbol", "Apple Symbols", "Noto Sans Symbols 2", "Noto Sans Symbols", "DejaVu Sans", sans-serif';
