import type { GestureId } from "@/types/study";

/**
 * GENERATED by scripts/sync_hud_symbols.py from the glasses HUD catalog
 * (catalog_version image_png_v1+octap+no_translate+octap_check_stacked+oc_order+cw_circles_svg(2026-10-01)). Do not edit by hand.
 *
 * `symbol` is the text the Rokid HUD prints for that gesture and `hudLabel` the short name beside it. A
 * gesture may instead carry `svg`, an inline drawing the HUD renders in the symbol's place - the two circle
 * gestures do, since a clockwise arrow with a circle exactly in its middle is not available as a glyph.
 */
export interface HudMark { symbol: string; hudLabel: string; svg?: string }

export const hudMarks: Record<GestureId, HudMark> = {
  OPS_TAP:         { symbol: "\u25cf", hudLabel: "TAP" },
  OPS_DOUBLE_TAP:  { symbol: "\u25c9", hudLabel: "DOUBLE TAP" },
  OPS_SWIPE_UP:    { symbol: "\u2191", hudLabel: "SWIPE UP" },
  OPS_SWIPE_DOWN:  { symbol: "\u2193", hudLabel: "SWIPE DOWN" },
  OPS_SWIPE_LEFT:  { symbol: "\u2190", hudLabel: "SWIPE LEFT" },
  OPS_SWIPE_RIGHT: { symbol: "\u2192", hudLabel: "SWIPE RIGHT" },
  OPS_CIRCLE:      { symbol: "\u21bb", hudLabel: "CIRCLE", svg: "<svg class=sv viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"23 4 23 10 17 10\"/><path d=\"M20.49 15a9 9 0 1 1-2.12-9.36L23 10\"/></svg>" },
  OC_TAP:          { symbol: "\u2713", hudLabel: "OBJ TAP" },
  OC_DOUBLE_TAP:   { symbol: "\u2713\n\u2713", hudLabel: "OBJ 2\u00d7TAP" },
  OC_TILT_UP:      { symbol: "\u2220\u2191", hudLabel: "TILT UP" },
  OC_TILT_DOWN:    { symbol: "\u2220\u2193", hudLabel: "TILT DOWN" },
  OC_TILT_LEFT:    { symbol: "\u2220\u2190", hudLabel: "TILT LEFT" },
  OC_TILT_RIGHT:   { symbol: "\u2220\u2192", hudLabel: "TILT RIGHT" },
  OC_CIRCLE:       { symbol: "\u21bb", hudLabel: "OBJ CIRCLE", svg: "<svg class=sv viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><polyline points=\"23 4 23 10 17 10\"/><path d=\"M20.49 15a9 9 0 1 1-2.12-9.36L23 10\"/><circle cx=\"12\" cy=\"12\" r=\"3.2\"/></svg>" },
};

/** Font stack that actually has these glyphs on Windows, macOS, Linux and Android. */
export const HUD_SYMBOL_FONT = '"Segoe UI Symbol", "Apple Symbols", "Noto Sans Symbols 2", "Noto Sans Symbols", "DejaVu Sans", sans-serif';
