# -*- coding: utf-8 -*-
"""Copy the glasses HUD's gesture symbols into the study app.

The Rokid HUD draws each recommended gesture as a symbol plus a terse label, both read from a gesture catalog that
brain_v4 builds its GSYM table from. The study must show the SAME marks, otherwise an expert judges one depiction
here and meets a different one on the glasses.

    python scripts/sync_hud_symbols.py

Writes data/hudSymbols.ts. The catalogs live in the private research repository and are not part of this one.
"""
import json, os, sys

if hasattr(sys.stdout, "reconfigure"): sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
REPO = os.path.dirname(APP)

# Two live programs each read a catalog and they are meant to stay identical: workingprototype_tapstrap/brain_v4.py
# reads the first, live_v4_gpt/brain_v4.py the second. Both are checked, so changing one cannot quietly leave the
# study showing the other's marks.
CATALOGS = [
    os.path.join(REPO, "workingprototype_tapstrap", "gesture_catalog.json"),
    os.path.join(REPO, "vlm_experiments", "web_experiment_01_VLMonly", "catalog", "gesture_catalog.json"),
]
CATALOG = CATALOGS[0]

# the study's card order: each family runs tap, double tap, the four directions, circle
GESTURE_IDS = [
    "OPS_TAP", "OPS_DOUBLE_TAP", "OPS_SWIPE_UP", "OPS_SWIPE_DOWN", "OPS_SWIPE_LEFT", "OPS_SWIPE_RIGHT", "OPS_CIRCLE",
    "OC_TAP", "OC_DOUBLE_TAP", "OC_TILT_UP", "OC_TILT_DOWN", "OC_TILT_LEFT", "OC_TILT_RIGHT", "OC_CIRCLE",
]

NL = chr(10)


def main():
    for c in CATALOGS:
        if not os.path.exists(c):
            sys.exit("catalog not found: %s%sThis script only runs inside the research repository." % (c, NL))
    cat = json.load(open(CATALOG, encoding="utf-8"))
    by_id = {g["id"]: g for g in cat["gestures"]}

    missing = [g for g in GESTURE_IDS if g not in by_id]
    if missing:
        sys.exit("catalog is missing: %s" % ", ".join(missing))
    extra = [g for g in by_id if g not in GESTURE_IDS]
    if extra:
        print("note: catalog also has %s (not used by the study)" % ", ".join(extra))

    # every live catalog must agree, or the study would match one HUD and not the other
    for c in CATALOGS[1:]:
        other = {g["id"]: g.get("symbol") for g in json.load(open(c, encoding="utf-8"))["gestures"]}
        bad = [(g, by_id[g].get("symbol"), other.get(g)) for g in GESTURE_IDS if other.get(g) != by_id[g].get("symbol")]
        if bad:
            rows = NL.join("    %-16s %s vs %s" % (g, a, b) for g, a, b in bad)
            sys.exit("live catalogs disagree:%s  %s%s  %s%s%s" % (NL, CATALOG, NL, c, NL, rows))
    print("%d live catalogs agree" % len(CATALOGS))

    rows = [(g, by_id[g]["symbol"], by_id[g]["label"]) for g in GESTURE_IDS]

    # the HUD may reuse one symbol for more than one gesture -> say so loudly rather than let it pass unnoticed
    seen = {}
    for gid, sym, _ in rows:
        seen.setdefault(sym, []).append(gid)
    clashes = {s: ids for s, ids in seen.items() if len(ids) > 1}

    out = [
        'import type { GestureId } from "@/types/study";',
        "",
        "/**",
        " * GENERATED by scripts/sync_hud_symbols.py from the glasses HUD catalog",
        " * (catalog_version %s). Do not edit by hand." % cat.get("catalog_version"),
        " *",
        " * `symbol` is exactly what the Rokid HUD prints for that gesture and `hudLabel` is the short name beside it,",
        " * so the depiction an expert judges here is the one they would see on the glasses.",
    ]
    if clashes:
        out.append(" *")
        out.append(" * NOTE. The HUD catalog gives these gestures the same symbol, so they cannot be told apart by mark alone:")
        for s, ids in clashes.items():
            out.append(" *   %s  %s" % (s, " / ".join(ids)))
    out += [
        " */",
        "export interface HudMark { symbol: string; hudLabel: string }",
        "",
        "export const hudMarks: Record<GestureId, HudMark> = {",
    ]
    width = max(len(g) for g in GESTURE_IDS)
    for gid, sym, lab in rows:
        # json.dumps, not a bare "%s": a symbol may carry a line break (the object double tap is two stacked checks)
        out.append("  %-*s { symbol: %s, hudLabel: %s }," % (width + 1, gid + ":", json.dumps(sym), json.dumps(lab)))
    out += [
        "};",
        "",
        "/** Font stack that actually has these glyphs on Windows, macOS, Linux and Android. */",
        "export const HUD_SYMBOL_FONT = '\"Segoe UI Symbol\", \"Apple Symbols\", \"Noto Sans Symbols 2\", \"Noto Sans Symbols\", \"DejaVu Sans\", sans-serif';",
        "",
    ]
    dst = os.path.join(APP, "data", "hudSymbols.ts")
    open(dst, "w", encoding="utf-8", newline=NL).write(NL.join(out))

    print("catalog_version %s -> data/hudSymbols.ts (%d gestures)" % (cat.get("catalog_version"), len(rows)))
    for i, (gid, sym, lab) in enumerate(rows, 1):
        print("  %2d  %-16s %-5s %s" % (i, gid, sym.replace(NL, "/"), lab))   # "/" stands in for a stacked mark
    if clashes:
        print("")
        print("WARNING: the HUD uses one symbol for several gestures:")
        for s, ids in clashes.items():
            print("  %s  %s" % (s, " / ".join(ids)))


if __name__ == "__main__":
    main()
