# -*- coding: utf-8 -*-
"""Copy the glasses HUD's gesture symbols into the study app.

The Rokid HUD draws each recommended gesture as a symbol plus a terse label, both read from
workingprototype_tapstrap/gesture_catalog.json (brain_v4.py builds its GSYM table from the same file). The study
must show the SAME marks, otherwise an expert judges one depiction here and sees a different one on the glasses.

    python scripts/sync_hud_symbols.py

Writes data/hudSymbols.ts. The catalog itself lives in the private research repository and is not part of this one.
"""
import json, os, sys

if hasattr(sys.stdout, "reconfigure"): sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
REPO = os.path.dirname(APP)
CATALOG = os.path.join(REPO, "workingprototype_tapstrap", "gesture_catalog.json")

GESTURE_IDS = [
    "OPS_TAP", "OPS_DOUBLE_TAP", "OPS_SWIPE_UP", "OPS_SWIPE_DOWN", "OPS_SWIPE_LEFT", "OPS_SWIPE_RIGHT", "OPS_CIRCLE",
    "OC_TILT_UP", "OC_TILT_DOWN", "OC_TILT_LEFT", "OC_TILT_RIGHT", "OC_TAP", "OC_DOUBLE_TAP", "OC_CIRCLE",
]


def main():
    if not os.path.exists(CATALOG):
        sys.exit("catalog not found: %s\nThis script only runs inside the research repository." % CATALOG)
    cat = json.load(open(CATALOG, encoding="utf-8"))
    by_id = {g["id"]: g for g in cat["gestures"]}

    missing = [g for g in GESTURE_IDS if g not in by_id]
    if missing:
        sys.exit("catalog is missing: %s" % ", ".join(missing))
    extra = [g for g in by_id if g not in GESTURE_IDS]
    if extra:
        print("note: catalog also has %s (not used by the study)" % ", ".join(extra))

    rows = [(g, by_id[g]["symbol"], by_id[g]["label"]) for g in GESTURE_IDS]

    # the HUD reuses one symbol for more than one gesture -> say so loudly rather than silently diverge
    seen = {}
    for gid, sym, _ in rows:
        seen.setdefault(sym, []).append(gid)
    clashes = {s: ids for s, ids in seen.items() if len(ids) > 1}

    out = [
        'import type { GestureId } from "@/types/study";',
        "",
        "/**",
        " * GENERATED by scripts/sync_hud_symbols.py from the glasses HUD catalog",
        " * (workingprototype_tapstrap/gesture_catalog.json, catalog_version %s). Do not edit by hand." % cat.get("catalog_version"),
        " *",
        " * `symbol` is exactly what the Rokid HUD prints for that gesture and `hudLabel` is the short name beside it,",
        " * so the depiction an expert judges here is the one they would see on the glasses.",
    ]
    if clashes:
        out.append(" *")
        out.append(" * NOTE. The HUD catalog gives these gestures the same symbol, so they are indistinguishable by mark alone:")
        for s, ids in clashes.items():
            out.append(" *   %s  %s" % (s, " / ".join(ids)))
    out += [
        " */",
        "export interface HudMark { symbol: string; hudLabel: string }",
        "",
        "export const hudMarks: Record<GestureId, HudMark> = {",
    ]
    width = max(len(g) for g in GESTURE_IDS)
    for gid, sym, lab in rows:
        out.append('  %-*s { symbol: "%s", hudLabel: "%s" },' % (width + 1, gid + ":", sym, lab))
    out += [
        "};",
        "",
        "/** Font stack that actually has these glyphs on Windows, macOS, Linux and Android. */",
        'export const HUD_SYMBOL_FONT = \'"Segoe UI Symbol", "Apple Symbols", "Noto Sans Symbols 2", "Noto Sans Symbols", "DejaVu Sans", sans-serif\';',
        "",
    ]
    dst = os.path.join(APP, "data", "hudSymbols.ts")
    open(dst, "w", encoding="utf-8", newline="\n").write("\n".join(out))

    print("catalog_version %s -> data/hudSymbols.ts (%d gestures)" % (cat.get("catalog_version"), len(rows)))
    for gid, sym, lab in rows:
        print("  %-16s %-3s %s" % (gid, sym, lab))
    if clashes:
        print("\nWARNING: the HUD uses one symbol for several gestures:")
        for s, ids in clashes.items():
            print("  %s  %s" % (s, " / ".join(ids)))


if __name__ == "__main__":
    main()
