# -*- coding: utf-8 -*-
"""Copy the glasses HUD's gesture marks into the study app.

The Rokid HUD draws each recommended gesture as a mark plus a terse label, read from a gesture catalog that brain_v4
builds its GSYM table from. The study must show the SAME marks, otherwise an expert judges one depiction here and
meets a different one on the glasses.

A mark is a `symbol`, optionally with an `inner` glyph drawn in the middle of it: the object circle is the thumb
circle with the object at its centre, because both gestures turn clockwise and direction cannot separate them.

    python scripts/sync_hud_symbols.py

Writes data/hudSymbols.ts. The catalogs live in the private research repository and are not part of this one.
"""
import json, os, sys

if hasattr(sys.stdout, "reconfigure"): sys.stdout.reconfigure(encoding="utf-8")
HERE = os.path.dirname(os.path.abspath(__file__))
APP = os.path.dirname(HERE)
REPO = os.path.dirname(APP)

# Two live programs each read a catalog and they are meant to stay identical: workingprototype_tapstrap/brain_v4.py
# reads the first, live_v4_gpt/brain_v4.py the second. Both are checked, so changing one cannot quietly leave the
# study showing the other's marks.
CATALOGS = [
    os.path.join(REPO, "workingprototype_tapstrap", "gesture_catalog.json"),
    os.path.join(REPO, "vlm_experiments", "web_experiment_01_VLMonly", "catalog", "gesture_catalog.json"),
]
CATALOG = CATALOGS[0]

# the study's card order: each family runs tap, double tap, the four directions, circle
GESTURE_IDS = [
    "OPS_TAP", "OPS_DOUBLE_TAP", "OPS_SWIPE_UP", "OPS_SWIPE_DOWN", "OPS_SWIPE_LEFT", "OPS_SWIPE_RIGHT", "OPS_CIRCLE",
    "OC_TAP", "OC_DOUBLE_TAP", "OC_TILT_UP", "OC_TILT_DOWN", "OC_TILT_LEFT", "OC_TILT_RIGHT", "OC_CIRCLE",
]

NL = chr(10)


def shown(sym, inner):
    """one-line form for the console: '/' is a line break in the mark, '+' is something drawn inside it"""
    return sym.replace(NL, "/") + ("+" + inner if inner else "")


def main():
    for c in CATALOGS:
        if not os.path.exists(c):
            sys.exit("catalog not found: %s%sThis script only runs inside the research repository." % (c, NL))
    cat = json.load(open(CATALOG, encoding="utf-8"))
    by_id = {g["id"]: g for g in cat["gestures"]}

    missing = [g for g in GESTURE_IDS if g not in by_id]
    if missing:
        sys.exit("catalog is missing: %s" % ", ".join(missing))
    extra = [g for g in by_id if g not in GESTURE_IDS]
    if extra:
        print("note: catalog also has %s (not used by the study)" % ", ".join(extra))

    def mark(g):
        return (g.get("symbol"), g.get("inner"))

    # every live catalog must agree, or the study would match one HUD and not the other
    for c in CATALOGS[1:]:
        other = {g["id"]: mark(g) for g in json.load(open(c, encoding="utf-8"))["gestures"]}
        bad = [(g, mark(by_id[g]), other.get(g)) for g in GESTURE_IDS if other.get(g) != mark(by_id[g])]
        if bad:
            lines = NL.join("    %-16s %s vs %s" % (g, shown(*a), shown(*b) if b else "missing") for g, a, b in bad)
            sys.exit("live catalogs disagree:%s  %s%s  %s%s%s" % (NL, CATALOG, NL, c, NL, lines))
    print("%d live catalogs agree" % len(CATALOGS))

    rows = [(g, by_id[g]["symbol"], by_id[g]["label"], by_id[g].get("inner")) for g in GESTURE_IDS]

    # a mark is the symbol plus whatever is drawn inside it, so the two clockwise circles are not a clash; a real
    # clash means two gestures a wearer cannot tell apart, which is worth saying loudly
    seen = {}
    for gid, sym, _, inner in rows:
        seen.setdefault((sym, inner), []).append(gid)
    clashes = {k: ids for k, ids in seen.items() if len(ids) > 1}

    out = [
        'import type { GestureId } from "@/types/study";',
        "",
        "/**",
        " * GENERATED by scripts/sync_hud_symbols.py from the glasses HUD catalog",
        " * (catalog_version %s). Do not edit by hand." % cat.get("catalog_version"),
        " *",
        " * `symbol` is exactly what the Rokid HUD prints for that gesture, `inner` is an optional glyph drawn in the",
        " * MIDDLE of it, and `hudLabel` is the short name beside it - so the depiction an expert judges here is the",
        " * one they would see on the glasses.",
    ]
    if clashes:
        out.append(" *")
        out.append(" * NOTE. The catalog gives these gestures the same mark, so they cannot be told apart by it alone:")
        for (sym, inner), ids in clashes.items():
            out.append(" *   %s  %s" % (shown(sym, inner), " / ".join(ids)))
    out += [
        " */",
        "export interface HudMark { symbol: string; hudLabel: string; inner?: string }",
        "",
        "export const hudMarks: Record<GestureId, HudMark> = {",
    ]
    width = max(len(g) for g in GESTURE_IDS)
    for gid, sym, lab, inner in rows:
        # json.dumps, not a bare "%s": a symbol may carry a line break (the object double tap is two stacked checks)
        extra = ", inner: %s" % json.dumps(inner) if inner else ""
        out.append("  %-*s { symbol: %s, hudLabel: %s%s }," % (width + 1, gid + ":", json.dumps(sym), json.dumps(lab), extra))
    out += [
        "};",
        "",
        "/** Font stack that actually has these glyphs on Windows, macOS, Linux and Android. */",
        "export const HUD_SYMBOL_FONT = '\"Segoe UI Symbol\", \"Apple Symbols\", \"Noto Sans Symbols 2\", \"Noto Sans Symbols\", \"DejaVu Sans\", sans-serif';",
        "",
    ]
    open(os.path.join(APP, "data", "hudSymbols.ts"), "w", encoding="utf-8", newline=NL).write(NL.join(out))

    print("catalog_version %s -> data/hudSymbols.ts (%d gestures)" % (cat.get("catalog_version"), len(rows)))
    for i, (gid, sym, lab, inner) in enumerate(rows, 1):
        print("  %2d  %-16s %-6s %s" % (i, gid, shown(sym, inner), lab))
    if clashes:
        print("")
        print("WARNING: these gestures share a mark:")
        for (sym, inner), ids in clashes.items():
            print("  %s  %s" % (shown(sym, inner), " / ".join(ids)))


if __name__ == "__main__":
    main()
